"""
STEP 68D — REBUILD LINEAMENT DENSITY RASTER
FROM EXISTING STATE-LEVEL STEP 40 RASTERS

Purpose:
- Reuse the original state-level lineament-density rasters
  generated by Step 40.
- Reproject them onto the final 250 m EPSG:6933 grid.
- Preserve NoData where no official Bhuvan lineament layer
  was available (Mizoram).
"""

from pathlib import Path

import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling


# ============================================================
# PATHS
# ============================================================
PROJECT = Path(r"C:\Users\Adrija\OneDrive\Desktop\landslide prj\Giri-rakshak-main")

FINAL_GRID = (
    PROJECT
    / "processed"
    / "step64a_final_ner_grid.tif"
)

NER_MASK = (
    PROJECT
    / "processed"
    / "step64a_final_ner_mask.tif"
)

LINEAMENT_DIR = (
    PROJECT
    / "raw_data"
    / "lineaments"
)

OUTPUT = (
    PROJECT
    / "processed"
    / "predictors"
    / "lineament_density_250m.tif"
)

SUMMARY = (
    PROJECT
    / "processed"
    / "step68d_lineament_raster_summary.csv"
)


# ============================================================
# STATE RASTERS
# ============================================================

STATE_RASTERS = {
    "Arunachal Pradesh":
        "arunachal_pradesh_lineament_density.tif",

    "Assam":
        "assam_lineament_density.tif",

    "Manipur":
        "manipur_lineament_density.tif",

    "Meghalaya":
        "meghalaya_lineament_density.tif",

    "Nagaland":
        "nagaland_lineament_density.tif",

    "Sikkim":
        "sikkim_lineament_density.tif",

    "Tripura":
        "tripura_lineament_density.tif",
}


# ============================================================
# CHECK INPUTS
# ============================================================

print("=" * 70)
print("STEP 68D — REBUILD LINEAMENT DENSITY RASTER")
print("=" * 70)

print("\nChecking input files...")

for state, filename in STATE_RASTERS.items():

    path = LINEAMENT_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"Missing raster for {state}: {path}"
        )

    print(f"  OK: {state}")
    print(f"      {filename}")


if not FINAL_GRID.exists():
    raise FileNotFoundError(
        f"Final grid not found:\n{FINAL_GRID}"
    )

if not NER_MASK.exists():
    raise FileNotFoundError(
        f"NER mask not found:\n{NER_MASK}"
    )


# ============================================================
# LOAD FINAL GRID
# ============================================================

print("\n" + "=" * 70)
print("LOADING FINAL GRID")
print("=" * 70)

with rasterio.open(FINAL_GRID) as grid_src:

    grid_crs = grid_src.crs
    grid_transform = grid_src.transform
    grid_width = grid_src.width
    grid_height = grid_src.height

    print(f"CRS: {grid_crs}")
    print(
        f"Size: {grid_width} x {grid_height}"
    )
    print(
        f"Resolution: "
        f"{grid_src.res}"
    )

    profile = grid_src.profile.copy()


# ============================================================
# LOAD NER MASK
# ============================================================

print("\nLoading NER mask...")

with rasterio.open(NER_MASK) as mask_src:

    if (
        mask_src.width != grid_width
        or mask_src.height != grid_height
    ):
        raise ValueError(
            "NER mask dimensions do not match final grid."
        )

    ner_mask = mask_src.read(1)

    print(
        f"Mask CRS: {mask_src.crs}"
    )

    valid_mask = ner_mask > 0

    print(
        f"NER valid cells: "
        f"{valid_mask.sum():,}"
    )


# ============================================================
# CREATE FINAL OUTPUT ARRAY
# ============================================================

# NaN internally represents NoData.
final_density = np.full(
    (grid_height, grid_width),
    np.nan,
    dtype=np.float32
)


# ============================================================
# PROCESS EACH STATE
# ============================================================

print("\n" + "=" * 70)
print("REPROJECTING STATE DENSITY RASTERS")
print("=" * 70)

state_stats = []

for state, filename in STATE_RASTERS.items():

    input_path = LINEAMENT_DIR / filename

    print("\n" + "-" * 70)
    print(state)
    print("-" * 70)

    with rasterio.open(input_path) as src:

        print(
            f"Source CRS: {src.crs}"
        )

        print(
            f"Source size: "
            f"{src.width} x {src.height}"
        )

        print(
            f"Source resolution: "
            f"{src.res}"
        )

        print(
            f"Source NoData: "
            f"{src.nodata}"
        )

        source = src.read(1).astype(
            np.float32
        )

        source_nodata = src.nodata

        # ----------------------------------------------------
        # Clean source values
        # ----------------------------------------------------

        if source_nodata is not None:

            source[
                source == source_nodata
            ] = np.nan

        # Remove non-finite values
        source[
            ~np.isfinite(source)
        ] = np.nan

        source_valid = np.isfinite(source)

        if source_valid.any():

            source_min = float(
                np.nanmin(source)
            )

            source_max = float(
                np.nanmax(source)
            )

            source_mean = float(
                np.nanmean(source)
            )

        else:

            source_min = np.nan
            source_max = np.nan
            source_mean = np.nan

        print(
            f"Source valid cells: "
            f"{source_valid.sum():,}"
        )

        print(
            f"Source min: {source_min:.6f}"
        )

        print(
            f"Source max: {source_max:.6f}"
        )

        print(
            f"Source mean: {source_mean:.6f}"
        )

        # ----------------------------------------------------
        # Reproject onto final grid
        # ----------------------------------------------------

        destination = np.full(
            (grid_height, grid_width),
            np.nan,
            dtype=np.float32
        )

        reproject(
            source=source,
            destination=destination,

            src_transform=src.transform,
            src_crs=src.crs,

            dst_transform=grid_transform,
            dst_crs=grid_crs,

            src_nodata=np.nan,
            dst_nodata=np.nan,

            resampling=Resampling.nearest
        )

        valid = np.isfinite(destination)

        print(
            f"Reprojected valid cells: "
            f"{valid.sum():,}"
        )

        if valid.any():

            print(
                f"Reprojected min: "
                f"{np.nanmin(destination):.6f}"
            )

            print(
                f"Reprojected max: "
                f"{np.nanmax(destination):.6f}"
            )

        # ----------------------------------------------------
        # Merge into final array
        # ----------------------------------------------------

        # Only fill cells that currently contain NoData.
        fill = (
            np.isnan(final_density)
            & valid
        )

        final_density[fill] = (
            destination[fill]
        )

        state_stats.append({
            "state": state,
            "source_valid_cells":
                int(source_valid.sum()),
            "reprojected_valid_cells":
                int(valid.sum()),
            "source_min":
                source_min,
            "source_max":
                source_max,
            "source_mean":
                source_mean,
        })


# ============================================================
# APPLY NER MASK
# ============================================================

print("\n" + "=" * 70)
print("APPLYING NER MASK")
print("=" * 70)

# Anything outside NER becomes NoData.
final_density[
    ~valid_mask
] = np.nan


# ============================================================
# FINAL STATISTICS
# ============================================================

valid_final = np.isfinite(
    final_density
)

valid_values = final_density[
    valid_final
]

print(
    f"Final valid cells: "
    f"{valid_final.sum():,}"
)

if valid_values.size > 0:

    print(
        f"Final min: "
        f"{valid_values.min():.6f}"
    )

    print(
        f"Final max: "
        f"{valid_values.max():.6f}"
    )

    print(
        f"Final mean: "
        f"{valid_values.mean():.6f}"
    )

    print(
        f"Final median: "
        f"{np.median(valid_values):.6f}"
    )

    print(
        f"Final std: "
        f"{valid_values.std():.6f}"
    )


# ============================================================
# WRITE OUTPUT
# ============================================================

print("\n" + "=" * 70)
print("WRITING FINAL RASTER")
print("=" * 70)

OUTPUT.parent.mkdir(
    parents=True,
    exist_ok=True
)

profile.update(
    driver="GTiff",
    dtype="float32",
    count=1,
    nodata=-9999.0,
    compress="deflate",
    predictor=3,
    tiled=False,
    BIGTIFF="IF_SAFER"
)

# Remove inherited block/tile settings from the final grid.
profile.pop("blockxsize", None)
profile.pop("blockysize", None)

output_array = np.where(
    np.isfinite(final_density),
    final_density,
    -9999.0
).astype(np.float32)


with rasterio.open(
    OUTPUT,
    "w",
    **profile
) as dst:

    dst.write(
        output_array,
        1
    )


print(
    f"\nSaved:\n{OUTPUT}"
)


# ============================================================
# SAVE SUMMARY
# ============================================================

import pandas as pd

summary_rows = []

for row in state_stats:
    summary_rows.append(row)

summary_rows.append({
    "state": "FINAL_NER",
    "source_valid_cells": np.nan,
    "reprojected_valid_cells":
        int(valid_final.sum()),
    "source_min":
        float(np.nanmin(valid_values))
        if valid_values.size else np.nan,
    "source_max":
        float(np.nanmax(valid_values))
        if valid_values.size else np.nan,
    "source_mean":
        float(np.nanmean(valid_values))
        if valid_values.size else np.nan,
})

summary_df = pd.DataFrame(
    summary_rows
)

summary_df.to_csv(
    SUMMARY,
    index=False
)

print(
    f"Summary saved:\n{SUMMARY}"
)


# ============================================================
# FINAL CHECK
# ============================================================

print("\n" + "=" * 70)
print("FINAL CHECK")
print("=" * 70)

with rasterio.open(OUTPUT) as check:

    arr = check.read(1)

    valid = arr != check.nodata

    print(
        f"CRS: {check.crs}"
    )

    print(
        f"Size: "
        f"{check.width} x {check.height}"
    )

    print(
        f"Resolution: "
        f"{check.res}"
    )

    print(
        f"NoData: "
        f"{check.nodata}"
    )

    print(
        f"Valid cells: "
        f"{valid.sum():,}"
    )

    if valid.any():

        vals = arr[valid]

        print(
            f"Min: "
            f"{vals.min():.6f}"
        )

        print(
            f"Max: "
            f"{vals.max():.6f}"
        )

        print(
            f"Mean: "
            f"{vals.mean():.6f}"
        )

print("\n" + "=" * 70)
print("STEP 68D COMPLETE")
print("=" * 70)